<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE schema_catalog [<!ELEMENT schema_catalog (schema)*><!ELEMENT schema (description? , identifier+)><!ATTLIST schema path CDATA #REQUIRED><!ATTLIST schema status CDATA #IMPLIED><!ELEMENT description (#PCDATA)><!ELEMENT identifier (label)><!ELEMENT label (#PCDATA)>]><schema_catalog><schema path="10303-203-aim-long.exp" status="IS"><description>This is the ISO 10303:203 Am1 (2000) EXPRESS schema. This schema file was downloaded from therepository maintained by STEP Tools Inc. (http://www.steptools.com/sc4/archive). This schema filewas CVS tag 1.3. This schema file copyrighted by ISO.</description><identifier><label>CONFIG_CONTROL_DESIGN</label></identifier></schema></schema_catalog>